INSERT INTO "PUBLIC_TEST"."USERS" ("EMAIL", "FIRST_NAME", "LAST_NAME") VALUES ('123@fi.co', '123', '098')
INSERT INTO "PUBLIC_TEST"."USERS" ("EMAIL", "FIRST_NAME", "LAST_NAME") VALUES ('456@fi.co', '345', '987')
INSERT INTO "PUBLIC_TEST"."USERS" ("EMAIL", "FIRST_NAME", "LAST_NAME") VALUES ('789@fi.co', '456', '765')